CC=g++
FILES=../src/Main.cpp ../src/BaseInputHandler.cpp ../src/Game.cpp ../src/Window.cpp ../src/InputHandler.cpp
FLAGS=-std=c++11 -lSDL2 -lSDL2_image
OUTPUT=game.o
all:
	$(CC) $(FILES) -o $(OUTPUT) $(FLAGS)
